package trabalhodsoo2.view;

import trabalhodsoo2.dao.PatchPanelDAO;
import trabalhodsoo2.dao.PortaDAO;
import trabalhodsoo2.dao.RackDAO;
import trabalhodsoo2.entity.PatchPanel;
import trabalhodsoo2.model.PortaTelefone;
import trabalhodsoo2.entity.Rack;
import trabalhodsoo2.entity.Porta;
import trabalhodsoo2.dao.TelefoneDAO;
import trabalhodsoo2.controller.TelefoneController;

import java.util.List;
import javax.swing.JOptionPane;

public class Adicionar_Telefone extends javax.swing.JInternalFrame {

    public Adicionar_Telefone() {
        initComponents();
        carregarRacks();
        limparCampos();
        this.pack();

        jComboBox1.addActionListener(e -> atualizarPatchPanels());
    }

    private void limparCampos() {
        jTextField1.setText("");
        jTextField2.setText(""); // Porta
        jTextField3.setText(""); // Localização
        jTextField4.setText(""); // Observação
        jTextField5.setText(""); // Tipo de cabo
        jTextField6.setText(""); // Uso destinado
        jCheckBox1.setSelected(false); // Ocupada
        jComboBox1.setSelectedIndex(-1); // Rack
        jComboBox2.removeAllItems(); // PatchPanel
    }

    private void carregarRacks() {
        RackDAO dao = new RackDAO();
        List<Rack> lista = dao.listar();
        jComboBox1.removeAllItems();
        for (Rack r : lista) {
            jComboBox1.addItem(r);
        }
    }

    private void atualizarPatchPanels() {
        Rack rack = (Rack) jComboBox1.getSelectedItem();
        if (rack == null) {
            jComboBox2.removeAllItems();
            return;
        }
        PatchPanelDAO dao = new PatchPanelDAO();
        List<PatchPanel> lista = dao.listarPorRackETipo(rack.getId(), "Telefone");
        jComboBox2.removeAllItems();
        for (PatchPanel p : lista) {
            jComboBox2.addItem(p);
        }
    }

    /**
     * Creates new form Adicionar_Telefone
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Adicionar  Porta Telefone");

        jLabel2.setText("Selecione um Rack:");

        jLabel3.setText("Selecione o seu respectivo Patch Panel:");

        jLabel4.setText("Insira a Porta:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Insira o ramal telefônico:");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Insira a cor do cabo:");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel7.setText("Localização de destino:");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel8.setText("Usuário final:");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel9.setText("Observações:");

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Ocupada?");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("Limpar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel5)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jLabel7)
                                                        .addComponent(jLabel8)
                                                        .addComponent(jLabel9)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jButton1)
                                                                        .addComponent(jCheckBox1))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jButton2))
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jTextField1)
                                                        .addComponent(jTextField2)
                                                        .addComponent(jTextField3)
                                                        .addComponent(jTextField4)
                                                        .addComponent(jTextField5)
                                                        .addComponent(jTextField6)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(65, 65, 65)
                                                .addComponent(jLabel1)))
                                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton1)
                                        .addComponent(jButton2))
                                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>                        

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {
        // Rack
        atualizarPatchPanels();
    }

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {
        // patch panel
    }

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
        // porta
    }

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {
        // ramal telefone
    }

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {
        // cor do cabo
    }

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {
        // localizacao
    }

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {
        // usuario
    }

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {
        // obs
    }

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {
        // ocupacao
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // limpar
        limparCampos();
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // salvar
        try {
            if (jComboBox1.getSelectedItem() == null || jComboBox2.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this, "Selecione o Rack e o Patch Panel.");
                return;
            }

            PortaTelefone telefone = new PortaTelefone();
            telefone.setTipo("Telefone");
            telefone.setCodigo(jTextField1.getText());
            telefone.setPorta(jTextField1.getText());
            telefone.setRamal(jTextField2.getText());
            telefone.setCorCabo(jTextField3.getText());
            telefone.setLocalizacao(jTextField4.getText());
            telefone.setUsuarioFinal(jTextField5.getText());
            telefone.setObservacao(jTextField6.getText());
            telefone.setOcupada(jCheckBox1.isSelected());

            Rack rack = (Rack) jComboBox1.getSelectedItem();
            PatchPanel patch = (PatchPanel) jComboBox2.getSelectedItem();
            telefone.setRackId(rack.getId());
            telefone.setPatchPanelId(patch.getId());
            String portaDigitada = jTextField3.getText(); // a porta que o usuário digitou
            TelefoneDAO dao = new TelefoneDAO();
            if (dao.portaOcupada(portaDigitada, patch.getId())) {
                JOptionPane.showMessageDialog(this, "Esta porta já está ocupada neste patch panel.");
                return;
            }
            dao.inserir(telefone);
            JOptionPane.showMessageDialog(this, "Porta de telefone adicionada com sucesso!");
            limparCampos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar porta: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<Rack> jComboBox1;
    private javax.swing.JComboBox<PatchPanel> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration                   
}
